export const PERMISSIONS = {
  CREATE_BOARD: "CREATE_BOARD",
  UPDATE_BOARD: "UPDATE_BOARD",
  DELETE_BOARD: "DELETE_BOARD",

  ADD_MEMBER: "ADD_MEMBER",
  REMOVE_MEMBER: "REMOVE_MEMBER",

  CREATE_CARD: "CREATE_CARD",
  MOVE_CARD: "MOVE_CARD",
};